# Generated by Django 2.1.5 on 2019-02-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=250)),
                ('hostel_type', models.BooleanField(default=True)),
                ('hostel_phone', models.CharField(max_length=100)),
                ('hostel_mobile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seater_type', models.IntegerField(max_length=10)),
                ('room_price', models.CharField(max_length=250)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelAdmin.Hostels')),
            ],
        ),
    ]
