# Generated by Django 2.1.5 on 2019-02-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelAdmin', '0002_auto_20190217_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='location',
        ),
        migrations.AddField(
            model_name='geography',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostelAdmin.Hostel'),
        ),
        migrations.AddField(
            model_name='geography',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geography',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostelAdmin.Location'),
        ),
        migrations.AddField(
            model_name='geography',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11),
        ),
    ]
