# Generated by Django 2.1.5 on 2019-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelAdmin', '0004_auto_20190316_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('G', 'Girls Hostel'), ('B', 'Boys Hostel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
