# Generated by Django 2.1.5 on 2019-04-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelAdmin', '0005_auto_20190319_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='location',
        ),
        migrations.AddField(
            model_name='hostel',
            name='additional',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostelAdmin.Location'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('B', 'Boys Hostel'), ('G', 'Girls Hostel')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Geography',
        ),
    ]
